.TH ARCH-BUILDS-EXAMPLE 1 "September 2026" "arch-builds-example 1.0.0" "User Commands"
.SH NAME
arch-builds-example \- demonstrate the Arch-Builds packaging standard
.SH SYNOPSIS
.B arch-builds-example
.RI [ option ]
.SH DESCRIPTION
.B arch-builds-example
is a harmless reference command used to test a complete Arch Linux package lifecycle.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display usage information.
.TP
.BR \-V ", " \-\-version
Display the installed version.
